#!/bin/bash

#   INFORMASI
# - Di bagian APP Config ada perintah untuk membuat database dan table tolong ubah sesuai kebutuhan


#   VARIABLE YANG DIGUNAKAN WAJIB DIGANTI
RDSmountpoint="database-1.cz0n6hr9s1r8.us-east-1.rds.amazonaws.com"
UsernameRDS="admin"
passwordRDS="12345678"
IpbackupServer="192.168.0.133"
pathSSH="/home/ubuntu"
fileNameSSH="lab.pem"
EFSmountpoint="/home/ubuntu/efs"

#Config Depedensi APP
sudo apt update
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get install nodejs -y
sudo apt-get install rsync build-essential mysql-client -y

#Show EFS Config
df -h

#APP Config
cd /home/ubuntu/ && git clone https://github.com/adinur21/ukk.git
cd ukk/ && npm install
npm install --save express
npm install -g nodemon
npm install -g cors
npm install -g body-parser

#Config Connection RDS
cd /home/ubuntu/ukk/src/model/
sudo cat <<EOF >dbConnection.js
const mySql = require("mysql")
const db = mySql.createPool({
  host: "$RDSmountpoint",
  user: "$UsernameRDS",
  password: "$passwordRDS",
  database: "cloud_api"
})

exports.db = db;
EOF

mysql -h "$RDSmountpoint" -u "$UsernameRDS" -p <<EOF
show databases;
create database cloud_api;
use cloud_api;
CREATE TABLE guru (
id_guru int(11) AUTO_INCREMENT PRIMARY KEY,
nama_guru varchar(255),
mapel_guru varchar(255),
sekolah_guru varchar(255)
);

INSERT INTO guru (nama_guru, mapel_guru, sekolah_guru) VALUES ('Adi','cloud','SMK Telkom Malang');
INSERT INTO guru (nama_guru, mapel_guru, sekolah_guru) VALUES ('MasNopal','SiPalingTekaje','SMK Telkom Nie Boss');
show tables;
SELECT * FROM guru;
EOF

#Config Cronjob
cat <<EOF > /tmp/cronjob
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/cronjob installed on Mon Oct  2 04:22:08 2023)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
#Rsync Backup Server
*/1 * * * * rsync -avz -e /home/ubuntu/ukk/ ubuntu@$IpbackupServer:/home/ubuntu/app-log

#Rsync EFS
*/1 * * * * rsync -avz -e /var/log/ $EFSmountpoint
EOF
# Mengubah izin berkas crontab
chmod 0600 /tmp/cronjob

# Mengganti crontab root dengan berkas yang baru
sudo crontab /tmp/cronjob -u root

#First run Cronjob
rsync -avz -e /home/ubuntu/ukk/ ubuntu@$IpbackupServer:/home/ubuntu/app-log
rsync -avz -e /var/log/ $EFSmountpoint

crontab -e